services:
  nango-db:
    image: postgres:16.0-alpine@sha256:acf5271bbecd4b8733f4e93959a8d2b536a57aeee6cc4b6a71890aaf646425b8
    environment:
      POSTGRES_DB: ${NANGO_DB_NAME}
      POSTGRES_PASSWORD: ${NANGO_DB_PASSWORD}
      POSTGRES_USER: ${NANGO_DB_USER}
    volumes:
      - ${NANGO_DATA_PATH}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks: [nango]
  nango-server:
    image: nangohq/nango-server:hosted-0.71.10@sha256:b4e96e827f8a27c6ab108602f1850325250ac31636db5cf392c1d08fde8a79c5
    platform: linux/amd64
    depends_on:
      nango-db:
        condition: service_healthy
    environment:
      NANGO_ENCRYPTION_KEY: ${NANGO_ENCRYPTION_KEY}
      NANGO_ADMIN_KEY: ${NANGO_ADMIN_KEY}
      NANGO_DB_USER: ${NANGO_DB_USER}
      NANGO_DB_PASSWORD: ${NANGO_DB_PASSWORD}
      NANGO_DB_HOST: nango-db
      NANGO_DB_NAME: ${NANGO_DB_NAME}
      NANGO_DB_SSL: "false"
      RECORDS_DATABASE_URL: postgresql://${NANGO_DB_USER}:${NANGO_DB_PASSWORD}@nango-db:5432/${NANGO_DB_NAME}
      SERVER_PORT: "3003"
      NANGO_SERVER_URL: ${NANGO_SERVER_URL}
      NANGO_PUBLIC_SERVER_URL: ${NANGO_SERVER_URL}
      NANGO_PUBLIC_CONNECT_URL: ${NANGO_PUBLIC_CONNECT_URL}
      NANGO_CONNECT_UI_PORT: "3009"
      FLAG_SERVE_CONNECT_UI: "true"
      FLAG_AUTH_ENABLED: "true"
      NANGO_DASHBOARD_USERNAME: ${NANGO_DASHBOARD_USERNAME}
      NANGO_DASHBOARD_PASSWORD: ${NANGO_DASHBOARD_PASSWORD}
      LOG_LEVEL: info
      NANGO_LOGS_ENABLED: "false"
      CSP_REPORT_ONLY: "true"
    ports:
      - ${NANGO_BIND}:${NANGO_HTTP_PORT}:3003
      - ${NANGO_BIND}:${NANGO_CONNECT_PORT}:3009
    networks: [nango]
networks:
  nango:
